if game.PlaceId == 155615604 then
	local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
	local Window = Library.CreateLib("Prison Life [BETA]", "Sentinel")
	local Main = Window:NewTab("Main")
	local Playerlol = Window:NewTab("Other")
	local player = game:GetService("Players").LocalPlayer
	local character = player.Character

	--MainScripts
	local Section1 = Main:NewSection("Main")
	local GunSection = Main:NewSection("Gun Mods")
	local KillSection = Main:NewSection("Kill Section")
	-- Script generated by SimpleSpy - credits to exx#9394

	local Settings = {
		['Material'] = Enum.Material.Neon, -- Material
		['Color'] = Color3.fromRGB(50, 164, 168), -- Color
		['Transparency'] = 0.7 -- 0 to 1 Transparency
	}

	local ScreenGui = Instance.new('ScreenGui', game.CoreGui) -- Create screengui
	ScreenGui.IgnoreGuiInset = true

	local ViewportFrame = Instance.new('ViewportFrame', ScreenGui) -- Create viewport and define properties
	ViewportFrame.CurrentCamera = workspace.CurrentCamera
	ViewportFrame.Size = UDim2.new(1,0,1,0)
	ViewportFrame.BackgroundTransparency = 1
	ViewportFrame.ImageTransparency = Settings.Transparency


	-- Functions
	local States = {}
	local Chasms = {} -- Array for storing parts

	function generateChasm(player) -- functions that generates chasms for the player specififed
		local Character = workspace:FindFirstChild(player.Name)
		
		if Character then
			for _,Part in pairs(Character:GetChildren()) do
				if Part:IsA('Part') or Part:IsA('MeshPart') then
					local Chasm = Part:Clone()
					
					for _,Child in pairs(Chasm:GetChildren()) do
						if Child:IsA('Decal') then
							Child:Destroy()
						end
					end
					
					Chasm.Parent = ViewportFrame
					Chasm.Material = Settings.Material
					Chasm.Color = Settings.Color
					Chasm.Anchored = true
					
					table.insert(Chasms, Chasm)
				end
			end
		end
	end

	function clearChasms() -- remove all chasms
		for _,Chasm in pairs(Chasms) do
			Chasm:Destroy()
		end
		
		Chasms = {}
	end


	local function giveForcefield()
		local character = game.Players.LocalPlayer.Character
		if character then
			local forceField = Instance.new("ForceField")
			forceField.Visible = true
			forceField.Parent = character
		end
	end


	local function GetPos()
		return game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame
	end

	local function GetCamPos()
		return workspace.CurrentCamera.CFrame
	end

	local function GetTeam()
		return game.Players.LocalPlayer.TeamColor.Name
	end

	local team = GetTeam()

	function Teleport(Player, Position)
		if Player == nil or Position == nil then return end
		local savedcf = GetPos()
		workspace.Remote.loadchar:InvokeServer()
		game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = savedcf
		workspace.Remote.ItemHandler:InvokeServer(workspace.Prison_ITEMS.giver["M9"].ITEMPICKUP)
		local CHAR = game.Players.LocalPlayer.Character
		CHAR.Humanoid.Name = "1"
		local c = CHAR["1"]:Clone()
		c.Name = "Humanoid"
		c.Parent = CHAR
		CHAR["1"]:Destroy()
		game.Workspace.CurrentCamera.CameraSubject = CHAR
		CHAR.Animate.Disabled = true
		wait()
		CHAR.Animate.Disabled = false
		CHAR.Humanoid.DisplayDistanceType = "None"
		game.Players.LocalPlayer:FindFirstChild("Backpack"):FindFirstChild("M9").Parent = CHAR
		local STOP = 0
		repeat wait(.1)
			STOP = STOP + 1
			game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = Player.Character.HumanoidRootPart.CFrame * CFrame.new(0, 0, 0.75)
		until (not game.Players.LocalPlayer.Character:FindFirstChild("M9") or not game.Players.LocalPlayer.Character.HumanoidRootPart or not Player.Character.HumanoidRootPart or not game.Players.LocalPlayer.Character.HumanoidRootPart.Parent or not Player.Character.HumanoidRootPart.Parent or STOP > 500) and STOP > 3
		local STOP_2 = 0
		repeat wait()
			STOP_2 = STOP_2 + 1
			game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = Position
		until STOP_2 > 10
		workspace.Remote.loadchar:InvokeServer()
		game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = savedcf
	end

	local function GetPlayer(String)
		if not String then return end
		local Yes = {}
		for _, Player in ipairs(game.Players:GetPlayers()) do
			if string.lower(Player.Name):match(string.lower(String)) or string.lower(Player.DisplayName):match(string.lower(String)) then
				table.insert(Yes, Player)
			end
		end
		if #Yes > 0 then
			return Yes[1]
		elseif #Yes < 1 then
			return nil
		end
	end

	function Arrest(Player, Time)
		local Time = Time or 1
		local savedcf = GetPos()
		local savedcamcf = GetCamPos()
		local savedteam = GetTeam()
		if Player then
			repeat wait()
				game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = Player.Character.HumanoidRootPart.CFrame * CFrame.new(0, 0, 1)
				for i = 1,Time do
					coroutine.wrap(function()
						workspace.Remote.arrest:InvokeServer(Player.Character.Head)
					end)()
				end
			until Player.Character:FindFirstChild("Head"):FindFirstChild("handcuffedGui")
		end
		workspace.Remote.loadchar:InvokeServer(nil, BrickColor.new(savedteam).Name)
		game.Players.LocalPlayer.Character.Humanoid.Sit = false
		game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = savedcf
		workspace.CurrentCamera.CFrame = savedcamcf
	end


	function Kill(Player)
		pcall(function()
			if Player.Character:FindFirstChild("ForceField") or not workspace:FindFirstChild(Player.Name) or not workspace:FindFirstChild(Player.Name):FindFirstChild("Head") or Player == nil or Player.Character.Parent ~= workspace then return end
			workspace.Remote.ItemHandler:InvokeServer(workspace.Prison_ITEMS.giver["Remington 870"].ITEMPICKUP)

			local MyTeam = GetTeam()
			if Player.TeamColor.Name == game.Players.LocalPlayer.TeamColor.Name then
				local savedcf = GetPos()
				local savedcamcf = GetCamPos()
				workspace.Remote.loadchar:InvokeServer(nil, BrickColor.random().Name)
				game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = savedcf
				workspace.CurrentCamera.CFrame = savedcamcf
				workspace.Remote.ItemHandler:InvokeServer(workspace.Prison_ITEMS.giver["Remington 870"].ITEMPICKUP)
			end

			local Gun = game.Players.LocalPlayer.Character:FindFirstChild("Remington 870") or game.Players.LocalPlayer.Backpack:FindFirstChild("Remington 870")

			local FireEvent = {
				[1] = {
					["RayObject"] = Ray.new(Vector3.new(), Vector3.new()), 
					["Distance"] = 0, 
					["Cframe"] = CFrame.new(), 
					["Hit"] = workspace[Player.Name].Head
				}, [2] = {
					["RayObject"] = Ray.new(Vector3.new(), Vector3.new()), 
					["Distance"] = 0, 
					["Cframe"] = CFrame.new(), 
					["Hit"] = workspace[Player.Name].Head
				}, [3] = {
					["RayObject"] = Ray.new(Vector3.new(), Vector3.new()), 
					["Distance"] = 0, 
					["Cframe"] = CFrame.new(), 
					["Hit"] = workspace[Player.Name].Head
				}, [4] = {
					["RayObject"] = Ray.new(Vector3.new(), Vector3.new()), 
					["Distance"] = 0, 
					["Cframe"] = CFrame.new(), 
					["Hit"] = workspace[Player.Name].Head
				}, [5] = {
					["RayObject"] = Ray.new(Vector3.new(), Vector3.new()), 
					["Distance"] = 0, 
					["Cframe"] = CFrame.new(), 
					["Hit"] = workspace[Player.Name].Head
				}, [6] = {
					["RayObject"] = Ray.new(Vector3.new(), Vector3.new()), 
					["Distance"] = 0, 
					["Cframe"] = CFrame.new(), 
					["Hit"] = workspace[Player.Name].Head
				}, [7] = {
					["RayObject"] = Ray.new(Vector3.new(), Vector3.new()), 
					["Distance"] = 0, 
					["Cframe"] = CFrame.new(), 
					["Hit"] = workspace[Player.Name].Head
				}, [8] = {
					["RayObject"] = Ray.new(Vector3.new(), Vector3.new()), 
					["Distance"] = 0, 
					["Cframe"] = CFrame.new(), 
					["Hit"] = workspace[Player.Name].Head
				}
			}

			game:GetService("ReplicatedStorage").ShootEvent:FireServer(FireEvent, Gun)
			Gun.Parent = game.Players.LocalPlayer.Character
			game.Players.LocalPlayer.Character["Remington 870"]:Destroy()
		end)
	end
	


	GunSection:NewDropdown("Gun Giver", "Gives the selected gun", {"AK-47", "M9", "Remington 870"}, function(currentOption)
		local A_1 = game:GetService("Workspace")["Prison_ITEMS"].giver[currentOption].ITEMPICKUP
        local Event = game:GetService("Workspace").Remote.ItemHandler
        Event:InvokeServer(A_1)
	end)

    GunSection:NewDropdown("Gun Mod", "Makes the gun op", {"M9", "Remington 870", "AK-47"}, function(weapon)
        local module = nil
        if game:GetService("Players").LocalPlayer.Backpack:FindFirstChild(weapon) then
            module = require(game:GetService("Players").LocalPlayer.Backpack[weapon].GunStates)
        elseif game:GetService("Players").LocalPlayer.Character:FindFirstChild(weapon) then
            module = require(game:GetService("Players").LocalPlayer.Character[weapon].GunStates)
        end
        if module ~= nil then
            module["MaxAmmo"] = 100000000
            module["CurrentAmmo"] = 100000000
            module["StoredAmmo"] = 100000000
            module["FireRate"] = 0.09
            module["Spread"] = 0
            module["Range"] = math.huge
            module["Bullets"] = 10
            module["ReloadTime"] = 0.000001
            module["AutoFire"] = true
        end
    end)

	enabled = false 
	KillSection:NewButton("EnableESP", "ESP", function()
		if enabled == false then
			enabled = true
			while game:GetService('RunService').RenderStepped:Wait() do -- loop this process
				clearChasms()
				
				for _,Player in pairs(game:GetService('Players'):GetPlayers()) do
					if Player ~= game:GetService('Players').LocalPlayer then
						generateChasm(Player)
					end
				end
			end
		elseif enabled == true then
			print("Esp Already activated")
		end
	end)

	Section1:NewButton("Destroy all Doors", "DestroyDoors", function()
		game.Workspace.Doors:Destroy()
	end)

	Section1:NewTextBox("Tp", "DestroyDoors", function(playername)
		local Player = GetPlayer(playername)
		if Player ~= nil then
			Teleport(GetPlayer(playername), game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame)
		else
			print("Player Not Found!")
		end
	end)

	KillSection:NewButton("Kill All", "kill all", function ()
	
		for i,v in pairs(game.Players:GetPlayers()) do
			if v ~= game.Players.LocalPlayer then
				Kill(v)
			end
		end
	end)

	KillSection:NewButton("Kill All Cops", "kill all", function ()
		for i,v in pairs(game.Players:GetPlayers()) do
			if v ~= game.Players.LocalPlayer then
				if v.TeamColor.Name == "Bright blue" then
					Kill(v)
				end
			end
		end
	end)

	KillSection:NewButton("Loop Kill All Cops", "kill all", function ()
		States.LoopKill_Guards = true
		while wait() do
			if States.LoopKill_Guards then
				for i,v in pairs(game.Teams.Guards:GetPlayers()) do
					if v ~= game.Players.LocalPlayer then
						pcall(function()
							if v.Character.Humanoid.Health > 0 and v.Character.Head and v.Character and v ~= nil then
								Kill(v)
							end
						end)
					end
				end
			end
		end
	end)

	KillSection:NewButton("Loop Kill All", "kill all", function ()
		States.LoopKill_Others = true
		while wait() do
			if States.LoopKill_Others then
				for i,v in pairs(game.Players:GetPlayers()) do
					if v ~= game.Players.LocalPlayer then
						pcall(function()
							if v.Character.Humanoid.Health > 0 and v.Character.Head and v.Character and v ~= nil then
								Kill(v)
							end
						end)
					end
				end
			end
		end
	end)

	KillSection:NewButton("UnLoop Kill All", "Unkill all", function ()
		States.LoopKill_Criminals = false
		States.LoopKill_Guards = false
		States.LoopKill_Inmates = false
		States.LoopKill_Others = false
	end)

	--Player things
	local Section2 = Playerlol:NewSection("Player")

	Section2:NewSlider("Walkspeed", "Changes your walk speed to a set amount.", 500, 0, function(s) -- 500 (MaxValue) | 0 (MinValue)
    	game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = s
	end)

	Section2:NewSlider("Jumppower", "Changes your jump power to a set amount.", 500, 0, function(s) -- 500 (MaxValue) | 0 (MinValue)
    	game.Players.LocalPlayer.Character.Humanoid.JumpPower = s
	end)


	Section2:NewButton("ArrestAll", "Arrest", function()
		for i,v in pairs(game.Players:GetPlayers()) do
			if v ~= game.Players.LocalPlayer then
				if v.TeamColor.Name == "Really red" then
					Arrest(v, 30)
				end
			end
		end
	end)


	Section2:NewButton("TP To Base", "TPToBase", function()
		game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-943.981506, 100.1523933, 2058.73462)
	end)

	Section2:NewButton("No-Clip", "No-Clip", function()
		Stepped = game:GetService("RunService").Stepped:Connect(function()
			for a, b in pairs(Workspace:GetChildren()) do
				if b.Name == game.Players.LocalPlayer.Name then
					for i, v in pairs(Workspace[game.Players.LocalPlayer.Name]:GetChildren()) do
						if v:IsA("BasePart") then
                		v.CanCollide = false
						end
					end
				end
			end
		end)
	end)

elseif game.PlaceId == 1537690962 then
local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
	local Window = Library.CreateLib("Bee Swarm [BETA]", "Sentinel")
	local Main = Window:NewTab("Main")
	local Playerlol = Window:NewTab("Other")
	local player = game:GetService("Players").LocalPlayer
	local character = player.Character

	--MainScripts
	local Section1 = Main:NewSection("Main")

	-- Functions

	local function GetPos()
		return game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame
	end


	local function GoToHiveAndSell()
		local savedcf = GetPos()
		local args = {
    		[1] = "ToggleHoneyMaking"
		}
		hives = game.Workspace.HivePlatforms:GetChildren()
		for i, v in pairs(hives) do
			lol = v.Circle.SurfaceGui.TextLabel
			if lol.Text == game.Players.LocalPlayer.Name then
				game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(lol.Parent.Parent.Position)
				wait(0.5)
				game:GetService("ReplicatedStorage").Events.PlayerHiveCommand:FireServer(unpack(args))
			end
		end	
		wait(25)
		game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = savedcf
	end

	-- Script generated by SimpleSpy - credits to exx#9394




	Section1:NewButton("AutoClick", "AutoClick", function()
		hives = game.Workspace.HivePlatforms:GetChildren()
		tool = game:GetService("Players").LocalPlayer.Character:FindFirstChildWhichIsA("Tool").ClickEvent

		while wait(0.5) do
			tool:FireServer() 
		end

	end)
	
	Section1:NewButton("AutoGrind", "TpToHive", function()
		while wait(80) do
			GoToHiveAndSell()
		end
	end)

end
